### ISSUE TITLE
qrfact() bugs

### ISSUE THREAD

**Issue by blakejohnson** [JuliaLang/LinearAlgebra.jl#22]
Some fun bugs in qrfact().

```
A = rand(16,16);
r1 = qrfact(A);
r2 = qrfact(A);
r1 == r2
```

returns false. I notice that r1 contains several NaNs. in the result.

Also, can get a segfault with:

```
A = rand(512, 512);
for ct = 1:100 @elapsed qrfact(A) end
```

My versioninfo:

```
Julia Version 0.2.0-prerelease+3310
Commit 08e7947* 2013-08-16 20:36:59 UTC
Platform Info:
  System: Darwin (x86_64-apple-darwin11.4.2)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

@dmbates @ViralBShah

**Comment by blakejohnson** [comment]
Also, @andreasnoackjensen

**Comment by andreasnoack** [comment]
The `NaN`s are there because only the upper triangle is used for storage of the factorization. Generally, I think it would be difficult to get `r1==r2` because of ulp differences in the LAPACK computations. I am unable to reproduce the segfault with the following setup

``` julia
Julia Version 0.2.0-prerelease+3326
Commit 50f37f1* 2013-08-19 10:43:59 UTC
Platform Info:
  System: Darwin (x86_64-apple-darwin12.4.0)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

**Comment by blakejohnson** [comment]
I see, so `r1` and `r2` may have completely different data in the lower triangle. Checking further, I see that

```
r1.vs == r2.vs
# and
triu(r1.T) == triu(r2.T)
```

So, the first issue is solved.

As far as the segfault, I have not rebuilt OpenBLAS since DYNAMIC_ARCH was enabled by default. It seems odd that would be relevant, though.

**Comment by ViralBShah** [comment]
Would the recent dlasd4 patch be relevant here?

**Comment by andreasnoack** [comment]
@blakejohnson In addition, I don't really know how `==` works for composite types. Even when the lower triangle is set to zero such that `r1.vs==r2.vs` and `r1.T==r2.T` I still get `r1!=r2`.

@ViralBShah I don't think so. `qrfact` uses `geqrt3` which doesn't call `dlasd4`.

**Comment by blakejohnson** [comment]
@andreasnoackjensen I'm not really sure what the default behavior of `==` is for a composite type, either. Jeff's docs update this past week suggests that new types ought to implement `==` or `isequal` themselves.

I can't reproduce the segfault on my home computer, either. I guess I will force a rebuild of OpenBLAS on my other machine and see what happens.

**Comment by blakejohnson** [comment]
Rebuilding OpenBLAS on my work computer had no effect; it still segfaults. I do notice one difference: both my home machine (and the machine @andreasnoackjensen tested on) have OpenBLAS built with DYNAMIC_ARCH. My work machine did not have this flag set even after rebuilding OpenBLAS.

**Comment by ViralBShah** [comment]
@blakejohnson Can you also try with MKL?

**Comment by blakejohnson** [comment]
@ViralBShah I don't have MKL on my mac. I did try this with MKL on linux and it worked just fine.

I am rebuilding OpenBLAS with DYNAMIC_ARCH=1 this morning to see if that is really involved.

**Comment by blakejohnson** [comment]
Well, DYNAMIC_ARCH appears not to matter. I still get the segfault.

I'm not sure what else to try here. The only thing else that I notice is different is that the machines where this works are running OS 10.8, whereas my work machine is 10.7.

**Comment by JeffBezanson** [comment]
I see some invalid reads in dgemm inside dgeqrt3:

```
==69777== Invalid read of size 8
==69777==    at 0xCD03069: dgemm_oncopy_NEHALEM (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0x2: ???
==69777==    by 0x9: ???
==69777==    by 0xC4D4295: dtrmm_LTUN (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0xC3A2CEF: dtrmm_ (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0xDAF4895: dgeqrt3_ (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0xC3A2617: dgemm_ (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0xDAF491E: dgeqrt3_ (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0xDAF4A7C: dgeqrt3_ (in /home/jeffb/julia/usr/lib/libopenblas.so)
==69777==    by 0x41CEAD5: ???
==69777==    by 0x41CE92A: ???
==69777==    by 0x5324597: jl_apply (julia.h:1022)
==69777==    by 0x5327CF2: jl_trampoline (builtins.c:816)
==69777==    by 0x531B958: jl_apply (julia.h:1022)
==69777==  Address 0x63b0a030 is 0 bytes after a block of size 864 alloc'd
==69777==    at 0x4C2B6CD: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==69777==    by 0x539B684: alloc_big (gc.c:348)
==69777==    by 0x539D1F9: allocobj (gc.c:977)
==69777==    by 0x538BB3D: _new_array_ (array.c:76)
```

**Comment by ViralBShah** [comment]
Cc: @xianyi

**Comment by xianyi** [comment]
```
A = rand(512, 512);
for ct = 1:100 @elapsed qrfact(A) end
```

Is it segfault on Linux? 
I think I need a C code to test dgeqrt3.

**Comment by ViralBShah** [comment]
Does not segfault on mac.

**Comment by blakejohnson** [comment]
It segfaults on _some_ macs. I'm really not sure what is the relevant difference between the two macs I am testing on. One is a Core 2 Duo and the other is a Core i5, so maybe that is relevant for the kernels chosen by OpenBLAS? The Core i5 machine is the one that segfaults. You can drop the `@elapsed` and I still see the problem.

**Comment by ViralBShah** [comment]
Can you try the system blas on both Macs and see if it works?

**Comment by xianyi** [comment]
@blakejohnson ，
Could you just compile OpenBLAS without DYNAMIC_ARCH=1？I think OpenBLAS run different kernels on the two macs.

**Comment by blakejohnson** [comment]
@ViralBShah Good suggestion: it works just fine with AppleBLAS.
@xianyi I have tried it with and without `DYNAMIC_ARCH = 1`. It segfaults in both cases.

Trying to run things through gdb, I end up with a truncated backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000001058ec908 in .L46 ()
(gdb) bt
#0  0x00000001058ec908 in .L46 ()
JuliaLang/julia#1  0x0000000000000000 in ?? ()
```

**Comment by blakejohnson** [comment]
@xianyi Looks like my particular Core i5 is a Westmere. So, OpenBLAS uses the NEHALEM kernels, right?

**Comment by xianyi** [comment]
Yes, it uses NEHALEM kernel.

**Comment by jiahao** [comment]
bump @blakejohnson - is this still an issue in 0.2-rc1?

**Comment by ViralBShah** [comment]
Marking 0.2 since we do need to fix it in the upcoming release, if it is still an issue.

**Comment by JeffBezanson** [comment]
Do we know how to fix this?

**Comment by ViralBShah** [comment]
BTW, doesn't crash for me. We should revisit this as soon as JuliaLang/julia#4565 is merged.

**Comment by blakejohnson** [comment]
I'll try this again on my work machine on Monday. I'm pretty confident that this is an OpenBLAS bug.

**Comment by ViralBShah** [comment]
JuliaLang/julia#4565 is merged, but `xGEQRT` will call `xGEQRT3` - so I don't expect anything to change.

**Comment by blakejohnson** [comment]
```
A = rand(512, 512);
for ct = 1:100 qrfact(A) end
```

still segfaults on my work machine.

**Comment by jiahao** [comment]
I can't reproduce the segfault on `0.2.0-rc1+74 x86_64-apple-darwin12.5.0`. Maybe it's a Lion issue?

**Comment by blakejohnson** [comment]
@jiahao do you have a Westmere or Nehalem CPU?

**Comment by blakejohnson** [comment]
A current backtrace from a segfault:

```
#0  0x0000000104b32748 in .L46 ()
JuliaLang/julia#1  0x0000000000000001 in ?? ()
JuliaLang/julia#2  0x000000010480fed9 in dgemm_ ()
JuliaLang/julia#3  0x0000000104e8f791 in dgeqrt3_ ()
JuliaLang/julia#4  0x00000001000ea182 in jl_alloc_array_1d (atype=Cannot access memory at address 0x1f0
) at array.c:304
```

**Comment by jiahao** [comment]
I have a Core i5-2557M quad-core, so it's a Sandy Bridge.

**Comment by blakejohnson** [comment]
@xianyi I assume a Sandy Bridge CPU _could_ run the Nehalem kernel. How can we force that kernel choice so that others can test this?

**Comment by xianyi** [comment]
Please build OpenBLAS with TARGET=NEHALEM

Xianyi

**Comment by jiahao** [comment]
fwiw, I was also unable to reproduce the segfault on my old work machine which is a Core 2 Duo (Penryn).

**Comment by xianyi** [comment]
I wrote an int64 dgeqrt3 test in C https://gist.github.com/xianyi/7350668 . It works fine on my Mac OSX 10.9.

I will try julia soon.

**Comment by blakejohnson** [comment]
@xianyi I modified your test to repeatedly call `dgerqrt3`: https://gist.github.com/blakejohnson/7356904

When I call this with arguments of 512 (size) and 100 (iterations), it runs to completion (no segfault), but it has the bizarre behavior that the first ~70 iterations complete very quickly, and then it slows down dramatically.

**Comment by xianyi** [comment]
@blakejohnson , I updated the code https://gist.github.com/xianyi/7350668 , which re-inited matrix A before dgerqrt3. It works smoothly on 100 iterations.

**Comment by xianyi** [comment]
@blakejohnson , please try OpenBLAS develop branch. I think I fixed this SEGFAULT bug.

**Comment by blakejohnson** [comment]
@xianyi Indeed, this no longer segfaults on my Westmere Core i5 with your patch.
